### ISSUE TITLE
What is Dynamic Shift?

### ISSUE THREAD

**Issue by nikenike114** [DenOfEquity/forgeFlux_dualPrompt#2]
What is Dynamic Shift?

**Comment by DenOfEquity** [comment]
It's a different method of calculating the way Shift affects the timestep sigmas. From brief testing, it seems to work very badly with higher Shift values, but may be better at low values. It's the way Forge calculates, so included for completeness / reproducibility. Dynamic Shift is the term *diffusers* uses.

**Comment by nikenike114** [comment]
> It's a different method of calculating the way Shift affects the timestep sigmas. From brief testing, it seems to work very badly with higher Shift values, but may be better at low values. It's the way Forge calculates, so included for completeness / reproducibility. Dynamic Shift is the term _diffusers_ uses.

thank you~ have a good day 👍
